image:
  pullPolicy: IfNotPresent
  repository: registry.gitlab.com/draganczukp/simply-shorten
  tag: 1-3@sha256:708680e2549f1e0dee554e7d041daa07f9b196829831ff1c268d607cc5e54afd
service:
  main:
    ports:
      main:
        port: 4567
        protocol: http
        targetPort: 4567
persistence:
  config:
    enabled: true
    mountPath: "/config/db"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            db_url: "/config/db/urls.sqlite"
            password: user
            username: pass
