image:
  pullPolicy: IfNotPresent
  repository: registry.gitlab.com/draganczukp/simply-shorten
  tag: 1-3@sha256:f5b9f105016d0c4c42d7109d2363459fc12d9379be8cfa9df20ffd66c6a18d08
service:
  main:
    ports:
      main:
        port: 4567
        protocol: http
        targetPort: 4567
persistence:
  config:
    enabled: true
    mountPath: "/config/db"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            db_url: "/config/db/urls.sqlite"
            password: user
            username: pass
